# Generated by Django 4.1.1 on 2022-09-23 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 21, 33, 36, 153834, tzinfo=datetime.timezone.utc)),
        ),
    ]
