# Generated by Django 4.1.1 on 2022-09-23 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_data_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 21, 49, 12, 604480, tzinfo=datetime.timezone.utc)),
        ),
    ]
